version: '3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
     - wp-content:/var/www/html/wp-content
    ports:
      - "${WP_PORT}:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST="${WP_DB_HOST}"
      - WORDPRESS_DB_USER="${WP_DB_USER}"
      - WORDPRESS_DB_PASSWORD="${WP_DB_PASS}"
      - WORDPRESS_DB_NAME="${WP_DB_NAME}"
volumes:
  wp-content: