version: '3'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - wordpress
    environment:
      - MARIADB_ROOT_PASSWORD="${MARIADB_ROOT_PASS}"
      - MARIADB_DATABASE="${WP_DATABASE}"
      - MYSQL_USER="${WP_DB_USER}"
      - MYSQL_PASSWORD="${WP_DB_PASS}"
    ports:
      - "${MARIADB_PORT}:3306"
  wordpress:
    image: wordpress:latest
    volumes:
     - wp-content:/var/www/html/wp-content
    restart: always
    depends_on:
      - "mariadb"
    networks:
      - wordpress
    environment:
      - WORDPRESS_DB_HOST="${WP_DB_HOST}"
      - WORDPRESS_DB_USER="${WP_DB_USER}"
      - WORDPRESS_DB_PASSWORD="${WP_DB_PASS}"
      - WORDPRESS_DB_NAME="${WP_DATABASE}"
    ports:
      - "${WP_PORT}:80"
volumes:
  mariadb:
  wp-content:
networks:
  wordpress: